### ISSUE TITLE
License

### ISSUE THREAD

**Issue by John-Colvin** [dsimcha/Plot2kill#15]
What license is this code covered by?

**Comment by jordisayol** [comment]
Boost license
https://github.com/dsimcha/Plot2kill/wiki/Overview

**Comment by John-Colvin** [comment]
Thanks. Any chance of a LICENSE file to make that more obvious?

**Comment by jordisayol** [comment]
Don't know, but a pull request can help

**Comment by John-Colvin** [comment]
https://github.com/dsimcha/Plot2kill/pull/17
