### ISSUE TITLE
error compiling plot2kill with dmd 2.059 beta and gtkd svn 948

### ISSUE THREAD

**Issue by jordisayol** [dsimcha/Plot2kill#4]
/usr/include/x86_64-linux-gnu/dmd/phobos/std/traits.d(114): Error: template std.traits.defaultInit(T) is not a function template

**Comment by dsimcha** [comment]
Thanks.  I usually test Plot2kill, as well as Dstats, with every beta.  I'll definitely look into this when I get around to doing my beta testing.

**Comment by dsimcha** [comment]
Fixed.

**Comment by jordisayol** [comment]
Properly works, thanks!
